// Code generated by ent, DO NOT EDIT.

package inquiry

import (
	"time"
)

const (
	// Label holds the string label denoting the inquiry type in the database.
	Label = "inquiry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldTel holds the string denoting the tel field in the database.
	FieldTel = "tel"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldIsConfirm holds the string denoting the is_confirm field in the database.
	FieldIsConfirm = "is_confirm"
	// Table holds the table name of the inquiry in the database.
	Table = "inquiries"
)

// Columns holds all SQL columns for inquiry fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldEmail,
	FieldTel,
	FieldContent,
	FieldIsConfirm,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// DefaultIsConfirm holds the default value on creation for the "is_confirm" field.
	DefaultIsConfirm bool
)
