FROM golang:1.15.2-alpine

COPY ./app /go/app

WORKDIR /go/app

RUN apk update \
    && apk add --no-cache git \
    && go build -o app \
    # hot reload
    && go get github.com/oxequa/realize

CMD ["realize", "start"]