version: "3.4"

services:
  postgres:
    container_name: go-api
    image: postgis/postgis:13-master
    ports:
      - 4432:5432
    environment:
      - DB_HOST=localhost
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PG_PASSWORD=postgres
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
      - ./db/data:/var/lib/postgresql/data
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
