-- create "companies" table
CREATE TABLE "companies" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying(30) NOT NULL, PRIMARY KEY ("id"));
-- create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "given_name" character varying(30) NOT NULL, "family_name" character varying(30) NOT NULL, "email" character varying(30) NULL, "age" integer NULL, "company_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "users_companies_company" FOREIGN KEY ("company_id") REFERENCES "companies" ("id") ON DELETE NO ACTION);
-- create index "user_given_name_family_name" to table: "users"
CREATE INDEX "user_given_name_family_name" ON "users" ("given_name", "family_name");
